### PR TITLE
update aframe

### PR DESCRIPTION
**Pull request by kellyselden**
passing but not working yet, don't know why.

### CODE REVIEW

**Comment by kellyselden** [comment]
@gabrielgrant Are you able to offer your eyes on this? Something with attribute parsing is screwed up.

**Comment by kellyselden** [comment]
cc @dantedallag

**Comment by evoactivity** [comment]
@kellyselden Adding `'renderer'` the conflictedComponents seems to get this into a working state.
`export const conflictedComponents = ['layout', 'renderer'];`

I'm guessing there may be other things in `AFrame.components` that should not be applied to every entity.

Even with this fix and having AFrame rendering the dummy app seems a tad buggy, not sure if this is down to some other issues with AFrame or if the dummy just needs updating.

**Comment by gabrielgrant** [comment]
Thanks for following up on this, and sorry for not getting back to it sooner. I'll see if i can make some time to dig into this again in the next few days

**Pull request merged**
